app_legacy_package:
    path: /package
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_packages
        permanent: true
        keepQueryParams: true

app_start:
    path: /
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300

app_fun:
    path: /fun
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300

app_impressum:
    path: /impressum
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300

app_privacy:
    path: /privacy-policy
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300

app_packages:
    path: /packages
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300

app_package:
    path: /packages/{package}
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300

app_compare_packages:
    path: /compare/packages
    methods: GET
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'index.html'
        sharedAge: 3600
        maxAge: 300
